@startuml
title MVP Deposit creation Container diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml



Container(Site, "Сайт банка", "React.js, PHP Laravel", "Подача заявок на депозит")
Container(ClientInternetBank, "Интернет-банк веб клиент", "React.js")
Container(BackendInternetBank, "Интернет-банк бэкенд", "ASP.NET MVC", "Проведением платежей и открытие текущих счетов (дебетовых карт)")
  
Container(ApiGateway, "Api Gateway", "Kong", "General entry point")  
Container_Boundary(CallCenterSystem, "Система кол-центра") {
  Container(CallCenterService, "Система кол-центра", "React.js, Java Spring Boot", "")
  ContainerDb(CallCenterDB, "База данных кол-центра", "PostgreSQL", "")
}
  

Container(MessageQueue, "Message Queue", "Kafka", "")
Container(NotificationService, "СМС-шлюз телеком-оператора")


Container_Boundary(DepositSystem, "Система по работе с депозитами") {
  Container(DepositService, "Сервис депозитов", "Java Spring Boot", "Сервис по работе с депозитами")
  Container(DepositCache, "Deposit cache", "Redis", "")
}
  
Container_Boundary(ABS, "АБС") {
  Container(ABSClient, "АБС клиент", "Delphi", "")
  ContainerDb(ABSDB, "База данных АБС", "Oracle", "")
}

System_Ext(Telekom, "Телеком-оператор", "")

Rel(Site, ApiGateway, "Makes API calls to", "https, json")
Rel(ClientInternetBank, ApiGateway, "Makes API calls to", "https, json")
Rel(ApiGateway, CallCenterService, "Makes API calls to", "https, json")
Rel(ApiGateway, BackendInternetBank, "Makes API calls to", "https, json")
Rel(ApiGateway, DepositService, "Makes Deposit API calls to", "https, json")

Rel(DepositService, MessageQueue, "Reads/Writes deposit creation events")
Rel(DepositService, ABSDB, "Reads/Writes data")
Rel(DepositService, DepositCache, "Reads/Writes data from cache")
Rel(CallCenterService, CallCenterDB, "Reads/Writes data")
Rel(ABSClient, ABSDB, "Reads/Writes data")
Rel(ABSClient, NotificationService, "Send SMS")
Rel(NotificationService, Telekom, "Send SMS")

@enduml